import axios from "axios";

import type { AnalysisResponse } from "@/types/analysis";
import { analyzeRepository } from "@/services/api";

function normalizeAnalysisResponse(payload: any): AnalysisResponse {
  if (payload && typeof payload === "object" && "analysis" in payload) {
    return payload as AnalysisResponse;
  }

  const linkedinShowcase =
    typeof payload?.linkedin_post === "string"
      ? payload.linkedin_post
      : typeof payload?.linkedin_showcase === "string"
        ? payload.linkedin_showcase
        : "";

  return {
    analysis: {
      project_purpose:
        typeof payload?.analysis?.project_purpose === "string"
          ? payload.analysis.project_purpose
          : "Repository analysis generated by the backend.",
      technologies:
        Array.isArray(payload?.analysis?.technologies) && payload.analysis.technologies.length > 0
          ? payload.analysis.technologies
          : [],
      features:
        Array.isArray(payload?.analysis?.features) && payload.analysis.features.length > 0
          ? payload.analysis.features
          : [],
      problems_solved:
        Array.isArray(payload?.analysis?.problems_solved) && payload.analysis.problems_solved.length > 0
          ? payload.analysis.problems_solved
          : [],
      technical_challenges:
        Array.isArray(payload?.analysis?.technical_challenges) && payload.analysis.technical_challenges.length > 0
          ? payload.analysis.technical_challenges
          : [],
      learning_outcomes:
        Array.isArray(payload?.analysis?.learning_outcomes) && payload.analysis.learning_outcomes.length > 0
          ? payload.analysis.learning_outcomes
          : [],
      future_improvements:
        Array.isArray(payload?.analysis?.future_improvements) && payload.analysis.future_improvements.length > 0
          ? payload.analysis.future_improvements
          : [],
    },
    linkedin_showcase: linkedinShowcase,
    technical_breakdown:
      typeof payload?.technical_breakdown === "string"
        ? payload.technical_breakdown
        : "The backend response did not include a technical breakdown.",
    carousel:
      Array.isArray(payload?.carousel) && payload.carousel.length > 0
        ? payload.carousel
        : [],
    resume_bullets:
      Array.isArray(payload?.resume_bullets) && payload.resume_bullets.length > 0
        ? payload.resume_bullets
        : [],
    portfolio_description:
      typeof payload?.portfolio_description === "string"
        ? payload.portfolio_description
        : "",
    hashtags:
      Array.isArray(payload?.hashtags) && payload.hashtags.length > 0
        ? payload.hashtags
        : [],
  };
}

export async function fetchAnalysis(repoUrl: string): Promise<AnalysisResponse> {
  try {
    const data = await analyzeRepository(repoUrl);
    return normalizeAnalysisResponse(data);
  } catch (error) {
    if (axios.isAxiosError(error)) {
      const detail = error.response?.data?.detail;
      const message =
        typeof detail === "string"
          ? detail
          : "The backend could not analyze this repository right now.";
      throw new Error(message);
    }

    throw error;
  }
}
